### ISSUE TITLE
Thank you for ACS

### ISSUE THREAD

**Issue by fredvs** [serbod/acs#1]
Hello.
I want to thank you for ACS.
I take inspiration from your code for the dsp filters of uos project ( https://github.com/fredvs/uos ).

I wanted to thank you before but did not find you.

I am happy that ACS is still alive.

Fred van Stappen.

**Comment by serbod** [comment]
Thanks! But I worked on audio in/out  and file in/out filters. For DSP filters please thanks Andrei Borovsky anb@symmetrica.net

**Comment by fredvs** [comment]
Ha, ok, i have sent him a email...

Many thanks to both...

Fre;D

**Comment by fredvs** [comment]
Aaaargh... ;-(
=> 

> This is an automatically generated Delivery Status Notification.
> Delivery to the following recipients failed.
> => anb@symmetrica.net

So, if you see Andrei Borovsky, say him thank-you from me... ;-)

Fre;D
