### ISSUE TITLE
Fix for CDPLAYER demo missing a LPR file

### ISSUE THREAD

**Issue by zeljkoavramovic** [serbod/acs#11]
I have created a project, fixed form OnCreate access violation, and application now compiles and starts fine. However when trying to run some DLL is reported to be missing on my Win10x64. Could you please take a look?
[cdplayer.zip](https://github.com/serbod/acs/files/2909337/cdplayer.zip)

**Comment by zeljkoavramovic** [comment]
CDRIPPER demo compiles but also reports a missing DLL (akrip32.dll). Maybe it's a similar issue?

**Comment by serbod** [comment]
Historically, ACS was Win32 only, and some related libs is also win32 only.
When I works on components, I has only win32 and Linux in VirtualBox.

**Comment by zeljkoavramovic** [comment]
Me too, but on my Win10x64 that dll is missing. It looks like this is the library that is needed:
https://sourceforge.net/projects/akrip/
You should probably mention it somewhere in demo form, or check if dll load fails and show error message.

**Comment by serbod** [comment]
Demo project file fixed
