### ISSUE TITLE
Problem with PLAYER demo

### ISSUE THREAD

**Issue by zeljkoavramovic** [serbod/acs#13]
Demo compiles fine, but when started it immediately shows error message:

> Project Lazarus Player Example raised exception class 'EReadError' with message: Property is read-only'

Tested GIT trunk version of ACS.

**Comment by serbod** [comment]
Can't reproduce. Can you provide more specific information? What platform, is DirecX used?

**Comment by zeljkoavramovic** [comment]
Sorry, with latest ACS trunk I can not reproduce so you can close this issue. However, latest trunk laz_acs.lpk can not be compiled on 32-bit Lazarus 2.0 fixes + FPC 3.0 fixes on Win10x64. I had to change it. Fix is attached.

[laz_acs.zip](https://github.com/serbod/acs/files/2923697/laz_acs.zip)
