### ISSUE TITLE
.dpk for Delphi

### ISSUE THREAD

**Issue by willemma** [serbod/acs#15]
Is there a .dpk file for using components with Delphi?

**Comment by serbod** [comment]
It was originally for Delphi, you can search for NewACS project. And
laz_acs sources is compatible with Delphi.

**Comment by serbod** [comment]
You can add .dpk and make pull-request.

**Comment by willemma** [comment]
Thanks for the prompt response. I found NEWAC https://github.com/CHERTS/newac - The components look the same but some of the old components are not there anymore. Such as TSoundIndicator, etc. 
I am trying to revive some code I wrote many years ago using NewAC, so will just use the new component set and build from scratch. Thanks for great components.
