### ISSUE TITLE
TAcsMemoryIn not correctly initialized.

### ISSUE THREAD

**Issue by CFTechno** [serbod/acs#18]
The variable BufStart is not set to 1 on create. This will generate an error in TAcsMemoryIn.GetData at the move command 
`
  Move(FBuffer[BufStart-1], ABuffer^, Result);
`

setting it to 1 at .Init() will solve it.  
```
procedure TAcsMemoryIn.Init();
begin
  inherited Init();
  BufEnd:=FDataSize;
  BufStart:=1;//fvd
end;
```

This will also solve the incorrect counters etc in the rest of the GetData procedure

**Comment by serbod** [comment]
Thank you very much for bugreport. Fixed!

**Comment by CFTechno** [comment]
you're welcome. Are you interested in an demo\example that uses the AcsMemoryIn ? Took me some days to get it working and looking back it was relative easy and not that much code :)

That being said is it possible that ACSMemory only supports 8bit ?
