### ISSUE TITLE
Wavemapper driver runs only a few Samples in Windows

### ISSUE THREAD

**Issue by tcs-ulli** [serbod/acs#2]

**Comment by serbod** [comment]
What Windows version? 32/64 bit? What samples?

**Comment by tcs-ulli** [comment]
Crashs with Wavemapper driver with all Input Sources after the first Block. 
With Acs 2.5 (initial commit) this dont happen. 
On 32bit Windows.

**Comment by tcs-ulli** [comment]
Crashs on acs_audio.inc Line 142:      Inc(Result, WH.dwBufferLength);

**Comment by serbod** [comment]
Ups, sorry, missed reply notifycation. Also, find some pull request..
With my new experience from last year, i will significally improve project at weekend.
