### ISSUE TITLE
It is not possible to compile in Linux (Ubuntu)

### ISSUE THREAD

**Issue by wilco2009** [serbod/acs#22]
It is not possible to compile in Linux (Ubuntu 20.04.3)+Lazarus 2.0.6.

shows the following errors:

Warning: other unit files search path (aka unit path) of "laz_acs 3.0.1" contains "/home/wilco/.lazarus/onlinepackagemanager/packages/acs/src/filters", which belongs to package "laz_acs_lib"
Warning: other unit files search path (aka unit path) of "laz_acs_lib 3.0.1" contains "/home/wilco/.lazarus/onlinepackagemanager/packages/acs/src/filters", which belongs to package "laz_acs"
Compilar paquete laz_acs_lib 3.0.1: Código de salida 1, Errores: 5, Sugerencias: 1
acs_cdrom.inc(280,20) Error: method identifier expected
acs_cdrom.inc(282,10) Error: Identifier not found "FLibLoaded"
acs_cdrom.inc(284,7) Error: Identifier not found "FLibLoaded"
acs_cdrom.inc(345,20) Error: function header doesn't match the previous declaration "Eject:Boolean;"
acs_cdrom.inc(356,20) Error: function header doesn't match the previous declaration "CloseTray:Boolean;"
acs_cdrom.pas(257,20) Hint: Local variable "CDM" does not seem to be initialized

In the code the following code is marked with error:
procedure TAcsCDIn.InitLib;
begin
  if not FLibLoaded then
    begin
      FLibLoaded:=True;
      CountDrives;
    end;
end;

**Comment by serbod** [comment]
This problem was already fixed, but in Lazarus OnlinePackageManager remains old version of ACS, that was tested for Windows.
Get fresh version from this repository.
