### ISSUE TITLE
FLAC decoder in pure Pascal?

### ISSUE THREAD

**Issue by Dingo64** [serbod/acs#27]
I found a FLAC decoder in pure Pascal. Might be a nice addition to the ACS.
https://github.com/jolonf/flac-pascal
There is, however, a small problem- it can only decode 16 bit FLAC files and has problems with 24/32 bit FLACs. But maybe you can something about it.

**Comment by serbod** [comment]
FLAC decoder added to ACS, adapted to little-endian numbers, fixed some range errors.

For 24/32 bit and high sample ratio on standart audio cards you need sample conversion. But, ACS sample converter filter capable to convert only 8/16 bit samples.

**Comment by Dingo64** [comment]
Great job, thanks!
