### ISSUE TITLE
GetAudioDeviceInfo on win64 breaks DeviceName

### ISSUE THREAD

**Issue by urame3** [serbod/acs#28]
\src\devices\win\acs_audio.inc
function GetAudioDeviceInfo

×  waveOutGetDevCaps waveInGetDevCaps
     multibyte characters returned by windowsANSI are broken

〇  waveOutGetDevCapsW waveInGetDevCapsW
 
 
function GetAudioDeviceInfo(DevID: Integer; OutputDev: Boolean): TAcsDeviceInfo;
var
  WIC:  WaveInCapsW;
  WOC:  WaveOutCapsW;
  ws:WideString;
  s:AnsiString;
begin
  if OutputDev then
  begin
    if DevID >= OutputChannelsCount then
      raise EAcsException.Create(Format(strChannelnotavailable, [DevId]));
  end
  else
  begin
    if DevID >= InputChannelsCount then
      raise EAcsException.Create(Format(strChannelnotavailable, [DevId]));
  end;
  if OutputDev then begin
    waveOutGetDevCapsW(DevID, @WOC, SizeOf(WOC));
    WIC.dwFormats:=WOC.dwFormats;
    WIC.wChannels:=WOC.wChannels;
    WIC.vDriverVersion:=WOC.vDriverVersion;
    ws:=WOC.szPname;
   end
  else  begin
    waveInGetDevCapsW(DevID, @WIC, SizeOf(WIC));
    ws:=WIC.szPname;
  end;

  s:=AnsiString(ws);
  s := PChar(s);
  Result.DeviceName:=s;
  Result.Formats:=[];
  if (WIC.dwFormats and WAVE_FORMAT_1M08) <> 0 then Result.Formats := Result.Formats + [af1M08];
  if (WIC.dwFormats and WAVE_FORMAT_1M16) <> 0 then Result.Formats := Result.Formats + [af1M16];
  if (WIC.dwFormats and WAVE_FORMAT_1S08) <> 0 then Result.Formats := Result.Formats + [af1S08];
  if (WIC.dwFormats and WAVE_FORMAT_1S16) <> 0 then Result.Formats := Result.Formats + [af1S16];
  if (WIC.dwFormats and WAVE_FORMAT_2M08) <> 0 then Result.Formats := Result.Formats + [af2M08];
  if (WIC.dwFormats and WAVE_FORMAT_2M16) <> 0 then Result.Formats := Result.Formats + [af2M16];
  if (WIC.dwFormats and WAVE_FORMAT_2S08) <> 0 then Result.Formats := Result.Formats + [af2S08];
  if (WIC.dwFormats and WAVE_FORMAT_2S16) <> 0 then Result.Formats := Result.Formats + [af2S16];
  if (WIC.dwFormats and WAVE_FORMAT_4M08) <> 0 then Result.Formats := Result.Formats + [af4M08];
  if (WIC.dwFormats and WAVE_FORMAT_4M16) <> 0 then Result.Formats := Result.Formats + [af4M16];
  if (WIC.dwFormats and WAVE_FORMAT_4S08) <> 0 then Result.Formats := Result.Formats + [af4S08];
  if (WIC.dwFormats and WAVE_FORMAT_4S16) <> 0 then Result.Formats := Result.Formats + [af4S16];
  Result.DrvVersion:=WIC.vDriverVersion;
  if WIC.wChannels = 1 then Result.Stereo:=False else Result.Stereo:=True;
end;

**Comment by serbod** [comment]
Fixed. Thank you very much for code example!
