### ISSUE TITLE
Compilation issues under Lazarus 1.8RC3

### ISSUE THREAD

**Issue by TudorHulban** [serbod/acs#7]
hi,
i have at least 10 compilation issues with Lazarus 1.8RC3. 
please advise if the code would be compiling under Lazarus 1.8RC3 64 bit.

for example directives as the below would not cover 64bit:
  {$IFDEF WIN32}
   Windows, ACS_Classes;
  {$ENDIF}

thank you

**Comment by tcs-ulli** [comment]
patches are welcome

**Comment by serbod** [comment]
TudorHulban, can you provide your compilator's output with any hints/warnings/errors?

Some parts of ACS is Windows-only, and maybe 32-bit only for some reasons, because original ACS was dedicated to Delphi and Win32. In most cases, it successfully works on Win64 as 32-bit application.

**Comment by serbod** [comment]
@TudorHulban I try to compile on Win64 Lazarus, and discover many problems. Some of external libraries (Monkey Audio, AKRip32) is 32-bit only, and many parts is not adapted to 64 bits. It will take some time to check and adapt every part. Until that, consider ACS for Windows is 32-bit only.
