### ISSUE TITLE
ACS conflicts with pl_win_directx

### ISSUE THREAD

**Issue by zeljkoavramovic** [serbod/acs#9]
As mentioned here: http://forum.lazarus.freepascal.org/index.php/topic,34297.msg310879.html#msg310879, both ACS and pl_win_directx can be downloaded with Lazarus Online Package Manager. Unfortunately, they both use same unit names as headers for DirectX, so we have duplicate units and Lazarus complains. The current workarounds are to either use only one or the other package, or to change ACS to use pl_win_directx instead of laz_directx package. I would like to fix this, so I am contacting you in hope to find a solution. If you don't like pl_win_directx package idea, then namespaces or some prefix could be used for all units. If you copy these units to some ACS subdir and rename them and distribute them with ACS then work is finished. Maybe you think that it would be a better idea to fix laz_directx package instead. I found laz_directx package here: https://github.com/cutec-chris/directx. If you confirm that is the one you are using then I can try to contact the author.

If you have any better idea how to solve this then I am all ears.

If you want to examine pl_win_directx package, then you can find it here:
https://bitbucket.org/avra/ct4laz/downloads/pl_win_directx.zip

Thank you very much for your nice components and your time to look around this issue!

**Comment by serbod** [comment]
I was aware about that problem and exclude directx units, but then return
then back. Don't remember why. Maybe, it related to OPM, where was no
directx package at that time. So, if directx package in OPM then just need
to add dependence in package config.

**Comment by zeljkoavramovic** [comment]
I have attached fixed laz_acs.lpk file which uses much richer pl_Win_DirectX package instead of laz_directx. Unfortunately PilotLogic has changed package name so it is not compatible with current OPM as old PilotLogic package name was pl_DirectX, and new name is pl_Win_DirectX. I have sent you LPK with new name, which will be available in OPM soon (after I finish conversion and testing of all current PilotLogic packages from latest CodeTyphon). After that unit name conflict will be gone.
[laz_acs_lpk_fix.zip](https://github.com/serbod/acs/files/2909499/laz_acs_lpk_fix.zip)

**Comment by serbod** [comment]
When I add pl_Win_DirectX dependency, ACS become incompatible with Linux. =( I think, there needed some optional package for DirectX only.

**Comment by zeljkoavramovic** [comment]
Wasn't that also the case with laz_directx.lpk?

How to solve this problem?

Making separate windows and linux packages is not an option since then each demo should include either one or the other package, so demos would be duplicated, too. Not a good solution.

The only solution I can see is to take Direct3D9 and other units to store them in some dir, rename them with some prefix, and $IFDEF them in uses section of your components and demos. That would avoid dependency on any DirectX package, similar to your older ACS version.

Do you have any better idea?

Please forgive me to bother you this much.

**Comment by serbod** [comment]
I already do some changes for compatibility:
- Removed DirectX dependancy and units from main package
* Separated Win32 and Win64 units

laz_acs.lpk will be win32/win64/linux compatible, but without DirectX
laz_acs_directx.lpk wil be optional, depends on laz_acs and laz_directx

**Comment by zeljkoavramovic** [comment]
Some projects like player need DirectX on Windows, but in project's requirement there is only laz_acs package so these demos no longer work on windows. Maybe you can save 2 same project files - one for windows (lpr with lpi which depends on laz_acs_directx) and one for linux (lpr with lpi which depends on laz_acs).

I still like more the idea to have same package for both windows and linux, and then directx units stored locally with some prefix.

Or even better, include separate INC file for windows and separate for linux.

Anyway, whatever you do I thank you for all the effort!

**Comment by serbod** [comment]
DirectX is optional. Base ACS components don't need it at all. It just
another 'drivers' for sound in/out and formats for file reader/writer. On
module all_formats is conditional include, that automatically enable all
DirectX modules, if them installed.
